### ISSUE TITLE
If ANET is above 100 I feel like you should show this image

### ISSUE THREAD

**Issue by dathelen** [osbjmg/isanetbelow60.com#10]
https://i.ytimg.com/vi/VdJZq4dRjf4/maxresdefault.jpg

**Comment by dathelen** [comment]
This issue is no longer relevant.  This was filled back in the early days when I didn't have so many different domains to choose from.  Please disregard.

**Comment by osbjmg** [comment]
After a super productive stand-up, we determined the path forward will be resolved via 2fe755dfdada6a6ff992f55a3a0eb074c0d54fe3.
